on:
  push:
    paths:
      - nlogox/**
      - .github/workflows/check-netlogo.yaml

name: check-netlogo.yaml
permissions: read-all

jobs:
  check-netlogo:
    if: "!contains(github.event.head_commit.message, '[skip check-netlogo]')"
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     config:
    #       - {os: windows-latest, version: 'release'}
    #       - {os: macos-latest, version: 'release'}
    #       - {os: ubuntu-latest, version: 'release'}
    # name: "${{ matrix.config.os }} (${{ matrix.config.version }})"
    # runs-on: ${{ matrix.config.os }}
    name: "Run Experiments"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: read-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up NetLogo
        uses: danielvartan/netlogo-actions/setup-netlogo@v1
        with:
          version: 'release'
          cache: 'true'

      - name: Check NetLogo models
        uses: danielvartan/netlogo-actions/check-netlogo@v1
