on:
  push:
    paths:
      - nlogox/**

name: check-netlogo.yaml
permissions: read-all

jobs:
  check-netlogo:
    if: "!contains(github.event.head_commit.message, '[skip check-netlogo]')"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, version: 'release'}
          - {os: macos-latest, version: 'release'}
          - {os: ubuntu-latest, version: 'release'}
    name: "${{ matrix.config.os }} (${{ matrix.config.version }})"
    runs-on: ${{ matrix.config.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: read-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore LogoClim test data cache
        id: logoclim-data-cache
        uses: actions/cache@v4
        with:
          path: "data"
          key: "logoclim-data"

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          # Install dependencies

          sudo apt-get update -qq >/dev/null
          sudo apt-get install -y -qq unzip >/dev/null
        shell: bash

      - name: Download LogoClim test data
        id: download-logoclim
        if: steps.logoclim-data-cache.outputs.cache-hit != 'true'
        run: |
          # Download LogoClim test data

          file="bra-10m.zip"
          url="https://osf.io/download/5a6y2/"

          curl \
            -L -o "$file" "$url" || \
            { echo "Error: Data download failed"; exit 1; }

          echo "file=$file" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Unzip LogoClim test data
        if: steps.logoclim-data-cache.outputs.cache-hit != 'true'
        run: |
          # Unzip LogoClim test data

          file="${{ steps.download-logoclim.outputs.file }}"
          dir="data"

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell \
            -Command "Expand-Archive -Path $file -DestinationPath $dir"

            rm -f "$file"
          else
            unzip "$file" -d "$dir"

            rm -f "$file"
          fi
        shell: bash

      - name: Set up NetLogo
        uses: danielvartan/netlogo-actions/setup-netlogo@v1
        with:
          version: ${{ matrix.config.version }}
          cache: 'true'

      - name: Check NetLogo models
        uses: danielvartan/netlogo-actions/check-netlogo@v1
